---
version: 3

images:
  base_image:
    name: ghcr.io/ansible-community/community-ee-minimal:latest

dependencies:
  galaxy: ee-requirements.yml
  python:
    - proxmoxer>=2.0.0
    - requests
  system:
    - git

additional_build_steps:
  prepend_galaxy:
    - RUN microdnf install -y git
