---
version: 3

images:
  base_image:
    name: ghcr.io/ansible/community-ee-minimal:latest

dependencies:
  galaxy: ee-requirements.yml
  python:
    - proxmoxer>=2.0.0
    - requests
  system:
    - git  # required for git+https collection installs
