---
# Stage 2 of 2: Wait for bare-metal nodes to boot from ISO, then install the cluster.
# Run this after baremetal-ocp-prepare.yml once all nodes have booted from the Discovery ISO.
- name: Install bare-metal OCP cluster
  hosts: baremetal-ocp-clusters
  gather_facts: false

  tasks:
    - name: Look up existing cluster_id
      rhpds.assisted_installer.list_clusters:
        offline_token: "{{ rh_console_offline_token }}"
      register: listclusters
      run_once: true

    - name: Set cluster_id from existing installer
      ansible.builtin.set_fact:
        cluster_id: "{{ listclusters.result | selectattr('name', 'equalto', cluster_name) | map(attribute='id') | last }}"

    - name: Print selected cluster_id
      ansible.builtin.debug:
        msg: "{{ cluster_id }}"

    - name: Wait for the hosts to be ready
      rhpds.assisted_installer.wait_for_hosts:
        cluster_id: "{{ cluster_id }}"
        offline_token: "{{ rh_console_offline_token }}"
        expected_hosts: "{{ groups[nodes_group] | length }}"
        wait_timeout: 300  # Usually ready in 3 - 4 minutes with "full" discovery ISO.
      register: wait_for_hosts
      until: wait_for_hosts.result.status == "ready"
      retries: 3  # On the off chance that the request fails.

    - name: Start cluster installation
      rhpds.assisted_installer.install_cluster:
        cluster_id: "{{ cluster_id }}"
        offline_token: "{{ rh_console_offline_token }}"
        wait_timeout: 1200

    - name: Obtain OpenShift cluster credentials
      register: credentials
      rhpds.assisted_installer.get_credentials:
        cluster_id: "{{ cluster_id }}"
        offline_token: "{{ rh_console_offline_token }}"

    - name: Display credentials
      ansible.builtin.debug:
        var: credentials.result
